# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'semantic'
require 'json'

default_platform(:android)

MANIFEST_LOCATION = "../app/src/main/AndroidManifest.xml"
RELEASE_LOCATION = "../../EXPO_RELEASE.json"

def upgrade_android_release
  releaseObject = JSON.parse(File.read(RELEASE_LOCATION))
  releaseObject["android"] += 1
  releaseNumber = releaseObject["android"]
  fileContents = File.read(MANIFEST_LOCATION)
  newContents = fileContents.gsub(/android-v\d+/, "android-v#{releaseNumber}")
  File.write(MANIFEST_LOCATION, newContents)
  File.write(RELEASE_LOCATION, releaseObject.to_json)
  # system("git commit -am 'Update to release channel android-v#{releaseNumber}'")
end

VERSION_CODE_REGEX = /versionCode (\d+)/
BUILD_GRADLE_LOCATION = "../app/build.gradle"

def upgrade_gradle_codes
  buildContents = File.read(BUILD_GRADLE_LOCATION)
  versionCode = buildContents.match(VERSION_CODE_REGEX)[1]
  versionCode += 1
  buildContents.gsub!(VERSION_CODE_REGEX, "versionCode #{versionCode}")

  File.write(BUILD_GRADLE_LOCATION, buildContents)
end


platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :update_version do
    # ensure_git_status_clean
    # upgrade_android_release
    upgrade_gradle_codes
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    ensure_git_status_clean

    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
