# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'semantic'
require 'json'

default_platform(:android)

manifestLocation = "../app/src/main/AndroidManifest.xml"
releaseLocation = "../../EXPO_RELEASE.json"

def upgrade_android_release
  releaseObject = JSON.parse(File.read(releaseLocation))
  releaseObject["android"] += 1
  releaseNumber = releaseObject["android"]
  fileContents = File.read(manifestLocation)
  newContents = fileContents.gsub(/android-v\d+/, "android-v#{releaseNumber}")
  File.write(manifestLocation, newContents)
  File.write(releaseLocation, releaseObject.to_json)
  # system("git commit -am 'Update to release channel android-v#{releaseNumber}'")
end


platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :update_version do
    ensure_git_status_clean
    upgrade_android_release
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    ensure_git_status_clean

    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
